name: mono_flutter
description: A Flutter plugin integrating the official android and ios SDK for Mono https://mono.co
version: 3.0.0
homepage: https://github.com/wiseminds/mono-flutter

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter  
  webview_flutter: ^4.7.0
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

 
flutter:
  plugin:
    implements: mono_flutter
    platforms:
      web:
        pluginClass: MonoFlutterWeb
        fileName: mono_flutter_web.dart
      ios:
        default_package: webview_flutter
      android:  
        default_package: webview_flutter
